//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.18 at 01:24:42 PM CET 
//


package it.unifi.ing.stlab.empedocle.services.mpi.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for assistenza complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="assistenza">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="asl_assistenza" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="asl_residenza" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cod_reg_medico" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cognome_medico" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nome_medico" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="asl_medico" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codfisc_medico" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="telefono_medico" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "assistenza", propOrder = {
    "aslAssistenza",
    "aslResidenza",
    "codRegMedico",
    "cognomeMedico",
    "nomeMedico",
    "aslMedico",
    "codfiscMedico",
    "telefonoMedico"
})
public class Assistenza {

    @XmlElement(name = "asl_assistenza", required = true)
    protected String aslAssistenza;
    @XmlElement(name = "asl_residenza", required = true)
    protected String aslResidenza;
    @XmlElement(name = "cod_reg_medico", required = true)
    protected String codRegMedico;
    @XmlElement(name = "cognome_medico", required = true)
    protected String cognomeMedico;
    @XmlElement(name = "nome_medico", required = true)
    protected String nomeMedico;
    @XmlElement(name = "asl_medico", required = true)
    protected String aslMedico;
    @XmlElement(name = "codfisc_medico", required = true)
    protected String codfiscMedico;
    @XmlElement(name = "telefono_medico", required = true)
    protected String telefonoMedico;

    /**
     * Gets the value of the aslAssistenza property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAslAssistenza() {
        return aslAssistenza;
    }

    /**
     * Sets the value of the aslAssistenza property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAslAssistenza(String value) {
        this.aslAssistenza = value;
    }

    /**
     * Gets the value of the aslResidenza property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAslResidenza() {
        return aslResidenza;
    }

    /**
     * Sets the value of the aslResidenza property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAslResidenza(String value) {
        this.aslResidenza = value;
    }

    /**
     * Gets the value of the codRegMedico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodRegMedico() {
        return codRegMedico;
    }

    /**
     * Sets the value of the codRegMedico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodRegMedico(String value) {
        this.codRegMedico = value;
    }

    /**
     * Gets the value of the cognomeMedico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCognomeMedico() {
        return cognomeMedico;
    }

    /**
     * Sets the value of the cognomeMedico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCognomeMedico(String value) {
        this.cognomeMedico = value;
    }

    /**
     * Gets the value of the nomeMedico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomeMedico() {
        return nomeMedico;
    }

    /**
     * Sets the value of the nomeMedico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomeMedico(String value) {
        this.nomeMedico = value;
    }

    /**
     * Gets the value of the aslMedico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAslMedico() {
        return aslMedico;
    }

    /**
     * Sets the value of the aslMedico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAslMedico(String value) {
        this.aslMedico = value;
    }

    /**
     * Gets the value of the codfiscMedico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodfiscMedico() {
        return codfiscMedico;
    }

    /**
     * Sets the value of the codfiscMedico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodfiscMedico(String value) {
        this.codfiscMedico = value;
    }

    /**
     * Gets the value of the telefonoMedico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelefonoMedico() {
        return telefonoMedico;
    }

    /**
     * Sets the value of the telefonoMedico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelefonoMedico(String value) {
        this.telefonoMedico = value;
    }

}
