//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.18 at 01:24:42 PM CET 
//


package it.unifi.ing.stlab.empedocle.services.mpi.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for identita.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="identita">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="sconosciuta"/>
 *     &lt;enumeration value="certificata"/>
 *     &lt;enumeration value="non certificata"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "identita")
@XmlEnum
public enum Identita {

    @XmlEnumValue("sconosciuta")
    SCONOSCIUTA("sconosciuta"),
    @XmlEnumValue("certificata")
    CERTIFICATA("certificata"),
    @XmlEnumValue("non certificata")
    NON_CERTIFICATA("non certificata");
    private final String value;

    Identita(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Identita fromValue(String v) {
        for (Identita c: Identita.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
