//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.18 at 01:24:42 PM CET 
//


package it.unifi.ing.stlab.empedocle.services.mpi.jaxb;

import java.time.LocalDate;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import it.unifi.ing.stlab.empedocle.actions.adapters.LocalDateAdapter;


/**
 * <p>Java class for indirizzo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="indirizzo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="indirizzo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="localita_frazione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="comune" type="{http://www.aou-careggi.toscana.it/thislab/eai/people/patient_identification}ente_territoriale" minOccurs="0"/>
 *         &lt;element name="provincia" type="{http://www.aou-careggi.toscana.it/thislab/eai/people/patient_identification}ente_territoriale" minOccurs="0"/>
 *         &lt;element name="regione" type="{http://www.aou-careggi.toscana.it/thislab/eai/people/patient_identification}ente_territoriale" minOccurs="0"/>
 *         &lt;element name="nazione" type="{http://www.aou-careggi.toscana.it/thislab/eai/people/patient_identification}ente_territoriale" minOccurs="0"/>
 *         &lt;element name="cap" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="data_variazione" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "indirizzo", propOrder = {
    "indirizzo",
    "localitaFrazione",
    "comune",
    "provincia",
    "regione",
    "nazione",
    "cap",
    "dataVariazione"
})
public class Indirizzo {

    protected String indirizzo;
    @XmlElement(name = "localita_frazione")
    protected String localitaFrazione;
    protected EnteTerritoriale comune;
    protected EnteTerritoriale provincia;
    protected EnteTerritoriale regione;
    protected EnteTerritoriale nazione;
    protected String cap;
    @XmlElement(name = "data_variazione")
    @XmlSchemaType(name = "date")
	@XmlJavaTypeAdapter( LocalDateAdapter.class )
    protected LocalDate dataVariazione;

    /**
     * Gets the value of the indirizzo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndirizzo() {
        return indirizzo;
    }

    /**
     * Sets the value of the indirizzo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndirizzo(String value) {
        this.indirizzo = value;
    }

    /**
     * Gets the value of the localitaFrazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalitaFrazione() {
        return localitaFrazione;
    }

    /**
     * Sets the value of the localitaFrazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalitaFrazione(String value) {
        this.localitaFrazione = value;
    }

    /**
     * Gets the value of the comune property.
     * 
     * @return
     *     possible object is
     *     {@link EnteTerritoriale }
     *     
     */
    public EnteTerritoriale getComune() {
        return comune;
    }

    /**
     * Sets the value of the comune property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnteTerritoriale }
     *     
     */
    public void setComune(EnteTerritoriale value) {
        this.comune = value;
    }

    /**
     * Gets the value of the provincia property.
     * 
     * @return
     *     possible object is
     *     {@link EnteTerritoriale }
     *     
     */
    public EnteTerritoriale getProvincia() {
        return provincia;
    }

    /**
     * Sets the value of the provincia property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnteTerritoriale }
     *     
     */
    public void setProvincia(EnteTerritoriale value) {
        this.provincia = value;
    }

    /**
     * Gets the value of the regione property.
     * 
     * @return
     *     possible object is
     *     {@link EnteTerritoriale }
     *     
     */
    public EnteTerritoriale getRegione() {
        return regione;
    }

    /**
     * Sets the value of the regione property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnteTerritoriale }
     *     
     */
    public void setRegione(EnteTerritoriale value) {
        this.regione = value;
    }

    /**
     * Gets the value of the nazione property.
     * 
     * @return
     *     possible object is
     *     {@link EnteTerritoriale }
     *     
     */
    public EnteTerritoriale getNazione() {
        return nazione;
    }

    /**
     * Sets the value of the nazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnteTerritoriale }
     *     
     */
    public void setNazione(EnteTerritoriale value) {
        this.nazione = value;
    }

    /**
     * Gets the value of the cap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCap() {
        return cap;
    }

    /**
     * Sets the value of the cap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCap(String value) {
        this.cap = value;
    }

    /**
     * Gets the value of the dataVariazione property.
     * 
     * @return
     *     possible object is
     *     {@link LocalDate }
     *     
     */
    public LocalDate getDataVariazione() {
        return dataVariazione;
    }

    /**
     * Sets the value of the dataVariazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalDate }
     *     
     */
    public void setDataVariazione(LocalDate value) {
        this.dataVariazione = value;
    }

}
