//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.18 at 01:24:42 PM CET 
//


package it.unifi.ing.stlab.empedocle.services.mpi.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for luogo_nascita complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="luogo_nascita">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.aou-careggi.toscana.it/thislab/eai/people/patient_identification}ente_territoriale">
 *       &lt;sequence>
 *         &lt;element name="provincia" type="{http://www.aou-careggi.toscana.it/thislab/eai/people/patient_identification}ente_territoriale" minOccurs="0"/>
 *         &lt;element name="nazione" type="{http://www.aou-careggi.toscana.it/thislab/eai/people/patient_identification}ente_territoriale" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "luogo_nascita", propOrder = {
    "provincia",
    "nazione"
})
public class LuogoNascita
    extends EnteTerritoriale
{

    protected EnteTerritoriale provincia;
    protected EnteTerritoriale nazione;

    /**
     * Gets the value of the provincia property.
     * 
     * @return
     *     possible object is
     *     {@link EnteTerritoriale }
     *     
     */
    public EnteTerritoriale getProvincia() {
        return provincia;
    }

    /**
     * Sets the value of the provincia property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnteTerritoriale }
     *     
     */
    public void setProvincia(EnteTerritoriale value) {
        this.provincia = value;
    }

    /**
     * Gets the value of the nazione property.
     * 
     * @return
     *     possible object is
     *     {@link EnteTerritoriale }
     *     
     */
    public EnteTerritoriale getNazione() {
        return nazione;
    }

    /**
     * Sets the value of the nazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnteTerritoriale }
     *     
     */
    public void setNazione(EnteTerritoriale value) {
        this.nazione = value;
    }

}
