//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.18 at 01:24:42 PM CET 
//


package it.unifi.ing.stlab.empedocle.services.mpi.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for merge_information complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="merge_information">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="patient_identifiers" type="{http://www.aou-careggi.toscana.it/thislab/eai/people/patient_identification}patient_identifiers"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "merge_information", namespace = "http://www.aou-careggi.toscana.it/thislab/eai/people/merge_information", propOrder = {
    "patientIdentifiers"
})
public class MergeInformation {

    @XmlElement(name = "patient_identifiers", required = true)
    protected PatientIdentifiers patientIdentifiers;

    /**
     * Gets the value of the patientIdentifiers property.
     * 
     * @return
     *     possible object is
     *     {@link PatientIdentifiers }
     *     
     */
    public PatientIdentifiers getPatientIdentifiers() {
        return patientIdentifiers;
    }

    /**
     * Sets the value of the patientIdentifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientIdentifiers }
     *     
     */
    public void setPatientIdentifiers(PatientIdentifiers value) {
        this.patientIdentifiers = value;
    }

}
