//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.18 at 01:24:42 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.aou-careggi.toscana.it/thislab/eai/people/patient_identification")
package it.unifi.ing.stlab.empedocle.services.mpi.jaxb;
