//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.18 at 01:24:42 PM CET 
//


package it.unifi.ing.stlab.empedocle.services.mpi.jaxb;

import java.time.LocalDate;
import java.time.LocalDateTime;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import it.unifi.ing.stlab.empedocle.actions.adapters.LocalDateAdapter;
import it.unifi.ing.stlab.empedocle.actions.adapters.LocalDateTimeAdapter;


/**
 * <p>Java class for patient_identification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="patient_identification">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="patient_identifiers" type="{http://www.aou-careggi.toscana.it/thislab/eai/people/patient_identification}patient_identifiers"/>
 *         &lt;element name="anonimo" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="intestazione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cognome" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cognome_acquisito" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nome" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="titolo_studio" type="{http://www.aou-careggi.toscana.it/thislab/eai/people/patient_identification}titolo_studio" minOccurs="0"/>
 *         &lt;element name="data_nascita" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="sesso" type="{http://www.aou-careggi.toscana.it/thislab/eai/people/patient_identification}sesso" minOccurs="0"/>
 *         &lt;element name="luogo_nascita" type="{http://www.aou-careggi.toscana.it/thislab/eai/people/patient_identification}luogo_nascita" minOccurs="0"/>
 *         &lt;element name="residenza" type="{http://www.aou-careggi.toscana.it/thislab/eai/people/patient_identification}indirizzo" minOccurs="0"/>
 *         &lt;element name="domicilio" type="{http://www.aou-careggi.toscana.it/thislab/eai/people/patient_identification}indirizzo" minOccurs="0"/>
 *         &lt;element name="recapiti" type="{http://www.aou-careggi.toscana.it/thislab/eai/people/patient_identification}recapiti" minOccurs="0"/>
 *         &lt;element name="stato_civile" type="{http://www.aou-careggi.toscana.it/thislab/eai/people/patient_identification}stato_civile" minOccurs="0"/>
 *         &lt;element name="cittadinanza" type="{http://www.aou-careggi.toscana.it/thislab/eai/people/patient_identification}cittadinanza" minOccurs="0"/>
 *         &lt;element name="data_decesso" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="identita" type="{http://www.aou-careggi.toscana.it/thislab/eai/people/patient_identification}identita" minOccurs="0"/>
 *         &lt;element name="certificazione_anagrafica" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="assistenza" type="{http://www.aou-careggi.toscana.it/thislab/eai/people/patient_identification}assistenza" minOccurs="0"/>
 *         &lt;element name="last_update" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "patient_identification", propOrder = {

})
public class PatientIdentification {

    @XmlElement(name = "patient_identifiers", required = true)
    protected PatientIdentifiers patientIdentifiers;
    protected Boolean anonimo;
    protected String intestazione;
    @XmlElement(required = true)
    protected String cognome;
    @XmlElement(name = "cognome_acquisito")
    protected String cognomeAcquisito;
    @XmlElement(required = true)
    protected String nome;
    @XmlElement(name = "titolo_studio")
    protected String titoloStudio;
    @XmlElement(name = "data_nascita")
    @XmlSchemaType(name = "date")
	@XmlJavaTypeAdapter( LocalDateAdapter.class )
    protected LocalDate dataNascita;
    @XmlSchemaType(name = "string")
    protected Sesso sesso;
    @XmlElement(name = "luogo_nascita")
    protected LuogoNascita luogoNascita;
    protected Indirizzo residenza;
    protected Indirizzo domicilio;
    protected Recapiti recapiti;
    @XmlElement(name = "stato_civile")
    @XmlSchemaType(name = "string")
    protected StatoCivile statoCivile;
    protected Cittadinanza cittadinanza;
    @XmlElement(name = "data_decesso")
    @XmlSchemaType(name = "dateTime")
	@XmlJavaTypeAdapter( LocalDateTimeAdapter.class )
    protected LocalDateTime dataDecesso;
    @XmlSchemaType(name = "string")
    protected Identita identita;
    @XmlElement(name = "certificazione_anagrafica")
    protected String certificazioneAnagrafica;
    protected Assistenza assistenza;
    @XmlElement(name = "last_update")
    @XmlSchemaType(name = "dateTime")
	@XmlJavaTypeAdapter( LocalDateTimeAdapter.class )    
    protected LocalDateTime lastUpdate;
    protected Long version;

    /**
     * Gets the value of the patientIdentifiers property.
     * 
     * @return
     *     possible object is
     *     {@link PatientIdentifiers }
     *     
     */
    public PatientIdentifiers getPatientIdentifiers() {
        return patientIdentifiers;
    }

    /**
     * Sets the value of the patientIdentifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientIdentifiers }
     *     
     */
    public void setPatientIdentifiers(PatientIdentifiers value) {
        this.patientIdentifiers = value;
    }

    /**
     * Gets the value of the anonimo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAnonimo() {
        return anonimo;
    }

    /**
     * Sets the value of the anonimo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAnonimo(Boolean value) {
        this.anonimo = value;
    }

    /**
     * Gets the value of the intestazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntestazione() {
        return intestazione;
    }

    /**
     * Sets the value of the intestazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntestazione(String value) {
        this.intestazione = value;
    }

    /**
     * Gets the value of the cognome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCognome() {
        return cognome;
    }

    /**
     * Sets the value of the cognome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCognome(String value) {
        this.cognome = value;
    }

    /**
     * Gets the value of the cognomeAcquisito property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCognomeAcquisito() {
        return cognomeAcquisito;
    }

    /**
     * Sets the value of the cognomeAcquisito property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCognomeAcquisito(String value) {
        this.cognomeAcquisito = value;
    }

    /**
     * Gets the value of the nome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNome() {
        return nome;
    }

    /**
     * Sets the value of the nome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNome(String value) {
        this.nome = value;
    }

    /**
     * Gets the value of the titoloStudio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitoloStudio() {
        return titoloStudio;
    }

    /**
     * Sets the value of the titoloStudio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitoloStudio(String value) {
        this.titoloStudio = value;
    }

    /**
     * Gets the value of the dataNascita property.
     * 
     * @return
     *     possible object is
     *     {@link LocalDate }
     *     
     */
    public LocalDate getDataNascita() {
        return dataNascita;
    }

    /**
     * Sets the value of the dataNascita property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalDate }
     *     
     */
    public void setDataNascita(LocalDate value) {
        this.dataNascita = value;
    }

    /**
     * Gets the value of the sesso property.
     * 
     * @return
     *     possible object is
     *     {@link Sesso }
     *     
     */
    public Sesso getSesso() {
        return sesso;
    }

    /**
     * Sets the value of the sesso property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sesso }
     *     
     */
    public void setSesso(Sesso value) {
        this.sesso = value;
    }

    /**
     * Gets the value of the luogoNascita property.
     * 
     * @return
     *     possible object is
     *     {@link LuogoNascita }
     *     
     */
    public LuogoNascita getLuogoNascita() {
        return luogoNascita;
    }

    /**
     * Sets the value of the luogoNascita property.
     * 
     * @param value
     *     allowed object is
     *     {@link LuogoNascita }
     *     
     */
    public void setLuogoNascita(LuogoNascita value) {
        this.luogoNascita = value;
    }

    /**
     * Gets the value of the residenza property.
     * 
     * @return
     *     possible object is
     *     {@link Indirizzo }
     *     
     */
    public Indirizzo getResidenza() {
        return residenza;
    }

    /**
     * Sets the value of the residenza property.
     * 
     * @param value
     *     allowed object is
     *     {@link Indirizzo }
     *     
     */
    public void setResidenza(Indirizzo value) {
        this.residenza = value;
    }

    /**
     * Gets the value of the domicilio property.
     * 
     * @return
     *     possible object is
     *     {@link Indirizzo }
     *     
     */
    public Indirizzo getDomicilio() {
        return domicilio;
    }

    /**
     * Sets the value of the domicilio property.
     * 
     * @param value
     *     allowed object is
     *     {@link Indirizzo }
     *     
     */
    public void setDomicilio(Indirizzo value) {
        this.domicilio = value;
    }

    /**
     * Gets the value of the recapiti property.
     * 
     * @return
     *     possible object is
     *     {@link Recapiti }
     *     
     */
    public Recapiti getRecapiti() {
        return recapiti;
    }

    /**
     * Sets the value of the recapiti property.
     * 
     * @param value
     *     allowed object is
     *     {@link Recapiti }
     *     
     */
    public void setRecapiti(Recapiti value) {
        this.recapiti = value;
    }

    /**
     * Gets the value of the statoCivile property.
     * 
     * @return
     *     possible object is
     *     {@link StatoCivile }
     *     
     */
    public StatoCivile getStatoCivile() {
        return statoCivile;
    }

    /**
     * Sets the value of the statoCivile property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatoCivile }
     *     
     */
    public void setStatoCivile(StatoCivile value) {
        this.statoCivile = value;
    }

    /**
     * Gets the value of the cittadinanza property.
     * 
     * @return
     *     possible object is
     *     {@link Cittadinanza }
     *     
     */
    public Cittadinanza getCittadinanza() {
        return cittadinanza;
    }

    /**
     * Sets the value of the cittadinanza property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cittadinanza }
     *     
     */
    public void setCittadinanza(Cittadinanza value) {
        this.cittadinanza = value;
    }

    /**
     * Gets the value of the dataDecesso property.
     * 
     * @return
     *     possible object is
     *     {@link LocalDateTime }
     *     
     */
    public LocalDateTime getDataDecesso() {
        return dataDecesso;
    }

    /**
     * Sets the value of the dataDecesso property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalDateTime }
     *     
     */
    public void setDataDecesso(LocalDateTime value) {
        this.dataDecesso = value;
    }

    /**
     * Gets the value of the identita property.
     * 
     * @return
     *     possible object is
     *     {@link Identita }
     *     
     */
    public Identita getIdentita() {
        return identita;
    }

    /**
     * Sets the value of the identita property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identita }
     *     
     */
    public void setIdentita(Identita value) {
        this.identita = value;
    }

    /**
     * Gets the value of the certificazioneAnagrafica property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificazioneAnagrafica() {
        return certificazioneAnagrafica;
    }

    /**
     * Sets the value of the certificazioneAnagrafica property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificazioneAnagrafica(String value) {
        this.certificazioneAnagrafica = value;
    }

    /**
     * Gets the value of the assistenza property.
     * 
     * @return
     *     possible object is
     *     {@link Assistenza }
     *     
     */
    public Assistenza getAssistenza() {
        return assistenza;
    }

    /**
     * Sets the value of the assistenza property.
     * 
     * @param value
     *     allowed object is
     *     {@link Assistenza }
     *     
     */
    public void setAssistenza(Assistenza value) {
        this.assistenza = value;
    }

    /**
     * Gets the value of the lastUpdate property.
     * 
     * @return
     *     possible object is
     *     {@link LocalDateTime }
     *     
     */
    public LocalDateTime getLastUpdate() {
        return lastUpdate;
    }

    /**
     * Sets the value of the lastUpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalDateTime }
     *     
     */
    public void setLastUpdate(LocalDateTime value) {
        this.lastUpdate = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVersion(Long value) {
        this.version = value;
    }

}
