//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.18 at 01:24:42 PM CET 
//


package it.unifi.ing.stlab.empedocle.services.mpi.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for patient_identifiers complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="patient_identifiers">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="id_ace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="id_dbsis" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="id_people" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="id_lis" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="id_archimed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="id_libprof" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="codice_fiscale" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tessera_sanitaria" type="{http://www.aou-careggi.toscana.it/thislab/eai/people/patient_identification}tessera_sanitaria" minOccurs="0"/>
 *         &lt;element name="tessera_TEAM" type="{http://www.aou-careggi.toscana.it/thislab/eai/people/patient_identification}tessera_TEAM" minOccurs="0"/>
 *         &lt;element name="tessera_STP" type="{http://www.aou-careggi.toscana.it/thislab/eai/people/patient_identification}tessera_STP" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "patient_identifiers", propOrder = {

})
public class PatientIdentifiers {

    @XmlElement(name = "id_ace")
    protected String idAce;
    @XmlElement(name = "id_dbsis")
    protected String idDbsis;
    @XmlElement(name = "id_people")
    protected String idPeople;
    @XmlElement(name = "id_lis")
    protected String idLis;
    @XmlElement(name = "id_archimed")
    protected String idArchimed;
    @XmlElement(name = "id_libprof")
    protected String idLibprof;
    @XmlElement(name = "codice_fiscale")
    protected String codiceFiscale;
    @XmlElement(name = "tessera_sanitaria")
    protected TesseraSanitaria tesseraSanitaria;
    @XmlElement(name = "tessera_TEAM")
    protected TesseraTEAM tesseraTEAM;
    @XmlElement(name = "tessera_STP")
    protected TesseraSTP tesseraSTP;

    /**
     * Gets the value of the idAce property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdAce() {
        return idAce;
    }

    /**
     * Sets the value of the idAce property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdAce(String value) {
        this.idAce = value;
    }

    /**
     * Gets the value of the idDbsis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdDbsis() {
        return idDbsis;
    }

    /**
     * Sets the value of the idDbsis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdDbsis(String value) {
        this.idDbsis = value;
    }

    /**
     * Gets the value of the idPeople property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdPeople() {
        return idPeople;
    }

    /**
     * Sets the value of the idPeople property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdPeople(String value) {
        this.idPeople = value;
    }

    /**
     * Gets the value of the idLis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdLis() {
        return idLis;
    }

    /**
     * Sets the value of the idLis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdLis(String value) {
        this.idLis = value;
    }

    /**
     * Gets the value of the idArchimed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdArchimed() {
        return idArchimed;
    }

    /**
     * Sets the value of the idArchimed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdArchimed(String value) {
        this.idArchimed = value;
    }

    /**
     * Gets the value of the idLibprof property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdLibprof() {
        return idLibprof;
    }

    /**
     * Sets the value of the idLibprof property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdLibprof(String value) {
        this.idLibprof = value;
    }

    /**
     * Gets the value of the codiceFiscale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceFiscale() {
        return codiceFiscale;
    }

    /**
     * Sets the value of the codiceFiscale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceFiscale(String value) {
        this.codiceFiscale = value;
    }

    /**
     * Gets the value of the tesseraSanitaria property.
     * 
     * @return
     *     possible object is
     *     {@link TesseraSanitaria }
     *     
     */
    public TesseraSanitaria getTesseraSanitaria() {
        return tesseraSanitaria;
    }

    /**
     * Sets the value of the tesseraSanitaria property.
     * 
     * @param value
     *     allowed object is
     *     {@link TesseraSanitaria }
     *     
     */
    public void setTesseraSanitaria(TesseraSanitaria value) {
        this.tesseraSanitaria = value;
    }

    /**
     * Gets the value of the tesseraTEAM property.
     * 
     * @return
     *     possible object is
     *     {@link TesseraTEAM }
     *     
     */
    public TesseraTEAM getTesseraTEAM() {
        return tesseraTEAM;
    }

    /**
     * Sets the value of the tesseraTEAM property.
     * 
     * @param value
     *     allowed object is
     *     {@link TesseraTEAM }
     *     
     */
    public void setTesseraTEAM(TesseraTEAM value) {
        this.tesseraTEAM = value;
    }

    /**
     * Gets the value of the tesseraSTP property.
     * 
     * @return
     *     possible object is
     *     {@link TesseraSTP }
     *     
     */
    public TesseraSTP getTesseraSTP() {
        return tesseraSTP;
    }

    /**
     * Sets the value of the tesseraSTP property.
     * 
     * @param value
     *     allowed object is
     *     {@link TesseraSTP }
     *     
     */
    public void setTesseraSTP(TesseraSTP value) {
        this.tesseraSTP = value;
    }

}
