//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.18 at 01:24:42 PM CET 
//


package it.unifi.ing.stlab.empedocle.services.mpi.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for stato_civile.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="stato_civile">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Non coniugato"/>
 *     &lt;enumeration value="Coniugato"/>
 *     &lt;enumeration value="Separato"/>
 *     &lt;enumeration value="Divorziato"/>
 *     &lt;enumeration value="Vedovo"/>
 *     &lt;enumeration value="Sconosciuto"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "stato_civile")
@XmlEnum
public enum StatoCivile {

    @XmlEnumValue("Non coniugato")
    NON_CONIUGATO("Non coniugato"),
    @XmlEnumValue("Coniugato")
    CONIUGATO("Coniugato"),
    @XmlEnumValue("Separato")
    SEPARATO("Separato"),
    @XmlEnumValue("Divorziato")
    DIVORZIATO("Divorziato"),
    @XmlEnumValue("Vedovo")
    VEDOVO("Vedovo"),
    @XmlEnumValue("Sconosciuto")
    SCONOSCIUTO("Sconosciuto");
    private final String value;

    StatoCivile(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StatoCivile fromValue(String v) {
        for (StatoCivile c: StatoCivile.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
