//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.18 at 01:24:42 PM CET 
//


package it.unifi.ing.stlab.empedocle.services.mpi.jaxb;

import java.time.LocalDate;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import it.unifi.ing.stlab.empedocle.actions.adapters.LocalDateAdapter;


/**
 * <p>Java class for tessera_TEAM complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tessera_TEAM">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numero_identificativo_tessera" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="istituzione" type="{http://www.aou-careggi.toscana.it/thislab/eai/people/patient_identification}istituzione"/>
 *         &lt;element name="nazione" type="{http://www.aou-careggi.toscana.it/thislab/eai/people/patient_identification}ente_territoriale"/>
 *         &lt;element name="data_scadenza" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="numero_identificativo_persona" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tessera_TEAM", propOrder = {
    "numeroIdentificativoTessera",
    "istituzione",
    "nazione",
    "dataScadenza",
    "numeroIdentificativoPersona"
})
public class TesseraTEAM {

    @XmlElement(name = "numero_identificativo_tessera", required = true)
    protected String numeroIdentificativoTessera;
    @XmlElement(required = true)
    protected Istituzione istituzione;
    @XmlElement(required = true)
    protected EnteTerritoriale nazione;
    @XmlElement(name = "data_scadenza", required = true)
    @XmlSchemaType(name = "date")
	@XmlJavaTypeAdapter( LocalDateAdapter.class )
    protected LocalDate dataScadenza;
    @XmlElement(name = "numero_identificativo_persona", required = true)
    protected String numeroIdentificativoPersona;

    /**
     * Gets the value of the numeroIdentificativoTessera property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroIdentificativoTessera() {
        return numeroIdentificativoTessera;
    }

    /**
     * Sets the value of the numeroIdentificativoTessera property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroIdentificativoTessera(String value) {
        this.numeroIdentificativoTessera = value;
    }

    /**
     * Gets the value of the istituzione property.
     * 
     * @return
     *     possible object is
     *     {@link Istituzione }
     *     
     */
    public Istituzione getIstituzione() {
        return istituzione;
    }

    /**
     * Sets the value of the istituzione property.
     * 
     * @param value
     *     allowed object is
     *     {@link Istituzione }
     *     
     */
    public void setIstituzione(Istituzione value) {
        this.istituzione = value;
    }

    /**
     * Gets the value of the nazione property.
     * 
     * @return
     *     possible object is
     *     {@link EnteTerritoriale }
     *     
     */
    public EnteTerritoriale getNazione() {
        return nazione;
    }

    /**
     * Sets the value of the nazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnteTerritoriale }
     *     
     */
    public void setNazione(EnteTerritoriale value) {
        this.nazione = value;
    }

    /**
     * Gets the value of the dataScadenza property.
     * 
     * @return
     *     possible object is
     *     {@link LocalDate }
     *     
     */
    public LocalDate getDataScadenza() {
        return dataScadenza;
    }

    /**
     * Sets the value of the dataScadenza property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalDate }
     *     
     */
    public void setDataScadenza(LocalDate value) {
        this.dataScadenza = value;
    }

    /**
     * Gets the value of the numeroIdentificativoPersona property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroIdentificativoPersona() {
        return numeroIdentificativoPersona;
    }

    /**
     * Sets the value of the numeroIdentificativoPersona property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroIdentificativoPersona(String value) {
        this.numeroIdentificativoPersona = value;
    }

}
