//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.18 at 01:24:42 PM CET 
//


package it.unifi.ing.stlab.empedocle.services.mpi.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tessera_sanitaria complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tessera_sanitaria">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numero_identificativo_tessera" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="regione_emittente" type="{http://www.aou-careggi.toscana.it/thislab/eai/people/patient_identification}ente_territoriale" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tessera_sanitaria", propOrder = {
    "numeroIdentificativoTessera",
    "regioneEmittente"
})
public class TesseraSanitaria {

    @XmlElement(name = "numero_identificativo_tessera", required = true)
    protected String numeroIdentificativoTessera;
    @XmlElement(name = "regione_emittente")
    protected EnteTerritoriale regioneEmittente;

    /**
     * Gets the value of the numeroIdentificativoTessera property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroIdentificativoTessera() {
        return numeroIdentificativoTessera;
    }

    /**
     * Sets the value of the numeroIdentificativoTessera property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroIdentificativoTessera(String value) {
        this.numeroIdentificativoTessera = value;
    }

    /**
     * Gets the value of the regioneEmittente property.
     * 
     * @return
     *     possible object is
     *     {@link EnteTerritoriale }
     *     
     */
    public EnteTerritoriale getRegioneEmittente() {
        return regioneEmittente;
    }

    /**
     * Sets the value of the regioneEmittente property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnteTerritoriale }
     *     
     */
    public void setRegioneEmittente(EnteTerritoriale value) {
        this.regioneEmittente = value;
    }

}
