//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.18 at 01:24:42 PM CET 
//


package it.unifi.ing.stlab.empedocle.services.mpi.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for update_person_information complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="update_person_information">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="message_header" type="{http://www.aou-careggi.toscana.it/thislab/eai/people/message_header}message_header"/>
 *         &lt;element name="patient_identification" type="{http://www.aou-careggi.toscana.it/thislab/eai/people/patient_identification}patient_identification"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "update_person_information", namespace = "http://www.aou-careggi.toscana.it/thislab/eai/people/update_person_information", propOrder = {
    "messageHeader",
    "patientIdentification"
})
public class UpdatePersonInformation {

    @XmlElement(name = "message_header", required = true)
    protected MessageHeader messageHeader;
    @XmlElement(name = "patient_identification", required = true)
    protected PatientIdentification patientIdentification;

    /**
     * Gets the value of the messageHeader property.
     * 
     * @return
     *     possible object is
     *     {@link MessageHeader }
     *     
     */
    public MessageHeader getMessageHeader() {
        return messageHeader;
    }

    /**
     * Sets the value of the messageHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageHeader }
     *     
     */
    public void setMessageHeader(MessageHeader value) {
        this.messageHeader = value;
    }

    /**
     * Gets the value of the patientIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link PatientIdentification }
     *     
     */
    public PatientIdentification getPatientIdentification() {
        return patientIdentification;
    }

    /**
     * Sets the value of the patientIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientIdentification }
     *     
     */
    public void setPatientIdentification(PatientIdentification value) {
        this.patientIdentification = value;
    }

}
